name: GitActionRelease

on:
  push:
    tags:
    - 'v*' # Triggers when a tag is pushed like "v1.0.0"

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    strategy:
      matrix:
        targetos: [win-x64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # 1. Publish EasySave (This embeds EasyLog.dll automatically)
    - name: Publish ProSoft
      run: dotnet publish ProSoft.csproj -c Release -r ${{ matrix.targetos }} --self-contained true -p:PublishSingleFile=true -o ./publish/${{ matrix.targetos }}/Bundle

    # 2. Publish CryptoSoft to the SAME folder
    - name: Publish CryptoSoft
      run: dotnet publish CryptoSoft/CryptoSoft.csproj -c Release -r ${{ matrix.targetos }} --self-contained true -p:PublishSingleFile=true -o ./publish/${{ matrix.targetos }}/Bundle

    # 3. Publish EasyLogServer to the SAME folder
    - name: Publish EasyLogServer
      run: dotnet publish EasyLogServer/EasyLogServer.csproj -c Release -r ${{ matrix.targetos }} --self-contained true -p:PublishSingleFile=true -o ./publish/${{ matrix.targetos }}/Bundle

    - name: Publish EasyLogServer (Linux for Docker)
      run: dotnet publish EasyLogServer/EasyLogServer.csproj -c Release -r linux-musl-x64 --self-contained true -p:PublishSingleFile=true -o ./publish/${{ matrix.targetos }}/Bundle/docker-build

    - name: Copy Docker files
      shell: pwsh
      run: |
        Copy-Item -Path "EasyLogServer/Dockerfile" -Destination "./publish/${{ matrix.targetos }}/Bundle/"
        Copy-Item -Path "EasyLogServer/docker-compose.yml" -Destination "./publish/${{ matrix.targetos }}/Bundle/"
    
    # 4. Zip the entire bundle together
    - name: Zip Output
      shell: pwsh
      run: |
        Compress-Archive -Path ".\publish\${{ matrix.targetos }}\Bundle\*" -DestinationPath "EasySave-Suite-${{ github.ref_name }}-${{ matrix.targetos }}.zip"

    # 5. Upload the single package to GitHub Releases
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          EasySave-Suite-${{ github.ref_name }}-${{ matrix.targetos }}.zip
